spring: 
  profiles: 
    active: 
    - dev

---
spring: 
  profiles: dev # 开发环境
  application: 
    name: mycloud-config-dev

---
spring: 
  profiles: test # 测试环境
  application: 
    name: mycloud-config-test
# 请保存为 UTF-8 格式